FROM alpine-java:base
MAINTAINER jorge.alemangonzalez@gmail.com
COPY build/libs/graphql-example-0.0.1-SNAPSHOT.jar /opt/spring-cloud/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/spring-cloud/lib/graphql-example-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080