version: '2'
services:
  books-server:
    container_name: books-server
    build:
      context: books-server/
      dockerfile: Dockerfile
    image: books-server:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    logging:
      driver: json-file
networks:
  spring-cloud-network:
    driver: bridge