// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package example;

import com.apollographql.apollo.api.*;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;
import com.apollographql.apollo.internal.QueryDocumentMinifier;
import com.apollographql.apollo.response.ScalarTypeAdapters;
import example.type.CustomType;
import okio.BufferedSource;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class BookByIdQuery implements Query<BookByIdQuery.Data, BookByIdQuery.Data, BookByIdQuery.Variables> {
  public static final String OPERATION_ID = "9e8bac2eb0a7014e2d8440dba0a5a82fa7f251d3fa212ba9a2e712d002e9f15f";

  public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
    "query BookById($id: ID) {\n"
        + "  bookById(id: $id) {\n"
        + "    __typename\n"
        + "    name\n"
        + "    pageCount\n"
        + "    author {\n"
        + "      __typename\n"
        + "      id\n"
        + "      firstName\n"
        + "      lastName\n"
        + "    }\n"
        + "  }\n"
        + "}"
  );

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "BookById";
    }
  };

  private final BookByIdQuery.Variables variables;

  public BookByIdQuery(@NotNull Input<String> id) {
    Utils.checkNotNull(id, "id == null");
    variables = new BookByIdQuery.Variables(id);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public BookByIdQuery.Data wrapData(BookByIdQuery.Data data) {
    return data;
  }

  @Override
  public BookByIdQuery.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<BookByIdQuery.Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  @Override
  @NotNull
  public Response<BookByIdQuery.Data> parse(@NotNull final BufferedSource source,
                                            @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<BookByIdQuery.Data> parse(@NotNull final BufferedSource source) throws
      IOException {
    return parse(source, ScalarTypeAdapters.DEFAULT);
  }

  public static final class Builder {
    private Input<String> id = Input.absent();

    Builder() {
    }

    public Builder id(@Nullable String id) {
      this.id = Input.fromNullable(id);
      return this;
    }

    public Builder idInput(@NotNull Input<String> id) {
      this.id = Utils.checkNotNull(id, "id == null");
      return this;
    }

    public BookByIdQuery build() {
      return new BookByIdQuery(id);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final Input<String> id;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(Input<String> id) {
      this.id = id;
      if (id.defined) {
        this.valueMap.put("id", id.value);
      }
    }

    public Input<String> id() {
      return id;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          if (id.defined) {
            writer.writeCustom("id", CustomType.ID, id.value != null ? id.value : null);
          }
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("bookById", "bookById", new UnmodifiableMapBuilder<String, Object>(1)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "id")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable BookById bookById;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable BookById bookById) {
      this.bookById = bookById;
    }

    public @Nullable BookById bookById() {
      return this.bookById;
    }

    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], bookById != null ? bookById.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "bookById=" + bookById
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.bookById == null) ? (that.bookById == null) : this.bookById.equals(that.bookById));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (bookById == null) ? 0 : bookById.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final BookById.Mapper bookByIdFieldMapper = new BookById.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final BookById bookById = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<BookById>() {
          @Override
          public BookById read(ResponseReader reader) {
            return bookByIdFieldMapper.map(reader);
          }
        });
        return new Data(bookById);
      }
    }
  }

  public static class BookById {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("name", "name", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("pageCount", "pageCount", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("author", "author", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String name;

    final @Nullable Integer pageCount;

    final @Nullable Author author;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public BookById(@NotNull String __typename, @Nullable String name, @Nullable Integer pageCount,
        @Nullable Author author) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.name = name;
      this.pageCount = pageCount;
      this.author = author;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String name() {
      return this.name;
    }

    public @Nullable Integer pageCount() {
      return this.pageCount;
    }

    public @Nullable Author author() {
      return this.author;
    }

    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], name);
          writer.writeInt($responseFields[2], pageCount);
          writer.writeObject($responseFields[3], author != null ? author.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "BookById{"
          + "__typename=" + __typename + ", "
          + "name=" + name + ", "
          + "pageCount=" + pageCount + ", "
          + "author=" + author
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof BookById) {
        BookById that = (BookById) o;
        return this.__typename.equals(that.__typename)
         && ((this.name == null) ? (that.name == null) : this.name.equals(that.name))
         && ((this.pageCount == null) ? (that.pageCount == null) : this.pageCount.equals(that.pageCount))
         && ((this.author == null) ? (that.author == null) : this.author.equals(that.author));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (name == null) ? 0 : name.hashCode();
        h *= 1000003;
        h ^= (pageCount == null) ? 0 : pageCount.hashCode();
        h *= 1000003;
        h ^= (author == null) ? 0 : author.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<BookById> {
      final Author.Mapper authorFieldMapper = new Author.Mapper();

      @Override
      public BookById map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String name = reader.readString($responseFields[1]);
        final Integer pageCount = reader.readInt($responseFields[2]);
        final Author author = reader.readObject($responseFields[3], new ResponseReader.ObjectReader<Author>() {
          @Override
          public Author read(ResponseReader reader) {
            return authorFieldMapper.map(reader);
          }
        });
        return new BookById(__typename, name, pageCount, author);
      }
    }
  }

  public static class Author {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("id", "id", null, true, CustomType.ID, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("firstName", "firstName", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("lastName", "lastName", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String id;

    final @Nullable String firstName;

    final @Nullable String lastName;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Author(@NotNull String __typename, @Nullable String id, @Nullable String firstName,
        @Nullable String lastName) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = id;
      this.firstName = firstName;
      this.lastName = lastName;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String id() {
      return this.id;
    }

    public @Nullable String firstName() {
      return this.firstName;
    }

    public @Nullable String lastName() {
      return this.lastName;
    }

    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[1], id);
          writer.writeString($responseFields[2], firstName);
          writer.writeString($responseFields[3], lastName);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Author{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "firstName=" + firstName + ", "
          + "lastName=" + lastName
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Author) {
        Author that = (Author) o;
        return this.__typename.equals(that.__typename)
         && ((this.id == null) ? (that.id == null) : this.id.equals(that.id))
         && ((this.firstName == null) ? (that.firstName == null) : this.firstName.equals(that.firstName))
         && ((this.lastName == null) ? (that.lastName == null) : this.lastName.equals(that.lastName));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (id == null) ? 0 : id.hashCode();
        h *= 1000003;
        h ^= (firstName == null) ? 0 : firstName.hashCode();
        h *= 1000003;
        h ^= (lastName == null) ? 0 : lastName.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Author> {
      @Override
      public Author map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[1]);
        final String firstName = reader.readString($responseFields[2]);
        final String lastName = reader.readString($responseFields[3]);
        return new Author(__typename, id, firstName, lastName);
      }
    }
  }
}
